api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.api, name='api'),

    path('doctor/', views.DoctorView.as_view(), name='doctor'),
    path('doctor/<int:pk>/', views.DoctorView.as_view(), name='doctor_detail'),
    path('doctor/<int:pk>/exercises/', views.DoctorView.as_view(), name='doctor_exercises'),
    path('doctor/<int:pk>/appoint/', views.DoctorView.as_view(), name='doctor_appoint'),

    path('patient/', views.PatientView.as_view(), name='patient'),
    path('patient/<int:pk>/', views.PatientView.as_view(), name='patient_detail'),
    path('patient/<int:pk>/exercises/', views.PatientView.as_view(), name='patient_exercises'),

    path('exercise/', views.ExerciseView.as_view(), name='exercise'),
    path('exercise/<int:pk>/', views.ExerciseView.as_view(), name='exercise_detail'),
]

urbanmedic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/models.py
from django.db import models


class Speciality(models.Model):
    """
    Сущность "Специальность".

    Attributes:
        title (CharField): Название специальности. Поле типа CharField, максимальная длина 64 символа.
    """

    title = models.CharField('title', max_length=64)

    def __str__(self):
        """
        Возвращает строковое представление объекта специальности.

        Returns:
            str: Строковое представление названия специальности.
        """
        return self.title


class Exercise(models.Model):
    """
    Сущность "Упражнение".

    Attributes:
        EVERY_HOUR (str): Константа для частоты выполнения "Каждый час".
        EVERY_DAY (str): Константа для частоты выполнения "Каждый день".
        EVERY_WEEK (str): Константа для частоты выполнения "Каждую неделю".
        EVERY_MONTH (str): Константа для частоты выполнения "Каждый месяц".
        EXERCISE_FREQUENCY (list of tuple): Список с кортежами частот выполнения упражнений.
            Каждый кортеж содержит два элемента: строковый идентификатор частоты и текстовое описание частоты.

        title (CharField): Название упражнения. Поле типа CharField, максимальная длина 128 символов.
        description (CharField): Описание упражнения. Поле типа CharField, максимальная длина 1024 символа.
        frequency (CharField): Частота выполнения упражнения. Поле типа CharField с ограниченными вариантами
            выбора из списка EXERCISE_FREQUENCY. По умолчанию установлено значение "Каждый день".
        specialisations (ManyToManyField): Связь с моделью Speciality для определения специализаций, к которым
            относится упражнение.

    Methods:
        __str__(): Возвращает строковое представление объекта упражнения (название упражнения).

    """
    EVERY_HOUR = 'every_hour'
    EVERY_DAY = 'every_day'
    EVERY_WEEK = 'every_week'
    EVERY_MONTH = 'every_month'

    EXERCISE_FREQUENCY = [
        (EVERY_HOUR, 'Каждый час'),
        (EVERY_DAY, 'Каждый день'),
        (EVERY_WEEK, 'Каждую неделю'),
        (EVERY_MONTH, 'Каждый месяц'),
    ]

    title = models.CharField('title', max_length=128)
    description = models.CharField('description', max_length=1024)
    frequency = models.CharField(
        'frequency',
        max_length=32,
        choices=EXERCISE_FREQUENCY,
        default=EVERY_DAY
    )
    specialisations = models.ManyToManyField(Speciality)

    def __str__(self):
        """
        Возвращает строковое представление объекта упражнения (название упражнения).

        Returns:
            str: Строковое представление названия упражнения.
        """
        return self.title


class Patient(models.Model):
    """
    Сущность "Пациент".

    Attributes:
        name (CharField): Имя пациента. Поле типа CharField, максимальная длина 128 символов.

    Methods:
        __str__(): Возвращает строковое представление объекта пациента (имя пациента).

    """
    name = models.CharField('name', max_length=128)

    def __str__(self):
        """
        Возвращает строковое представление объекта пациента (имя пациента).

        Returns:
            str: Строковое представление имени пациента.
        """
        return self.name


class Doctor(models.Model):
    """
    Сущность "Врач".

    Attributes:
        name (CharField): Имя врача. Поле типа CharField, максимальная длина 128 символов.
        speciality (ForeignKey): Специальность врача. Внешний ключ на модель Speciality,
                                 с вариантом удаления CASCADE.
        patients (ManyToManyField): Пациенты, связанные с врачом. Множественное отношение "многие ко многим"
                                   с моделью Patient.

    Methods:
        __str__(): Возвращает строковое представление объекта врача.

    """
    name = models.CharField('name', max_length=128)
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE)
    patients = models.ManyToManyField(Patient)

    def __str__(self):
        """
        Возвращает строковое представление объекта врача.

        Returns:
            str: Строковое представление объекта врача в формате "Имя: <имя врача>, Специальность: <специальность>".
        """
        return f"Имя: {self.name}, Специальность: {self.speciality}"


class Appointment(models.Model):
    """
    Сущность "Назначение".

    Attributes:
        doctor (ForeignKey): Внешний ключ на модель Doctor. Ссылается на врача, связанного с назначением.
                             С вариантом удаления CASCADE, что означает удаление связанного назначения при удалении врача.
        patient (ForeignKey): Внешний ключ на модель Patient. Ссылается на пациента, связанного с назначением.
                              С вариантом удаления CASCADE, что означает удаление связанного назначения при удалении пациента.
        exercise (ForeignKey): Внешний ключ на модель Exercise. Ссылается на упражнение, связанное с назначением.
                               С вариантом удаления CASCADE, что означает удаление связанного назначения при удалении упражнения.
        appointment_date (DateTimeField): Дата назначения упражнения. Поле типа DateTimeField.

    Methods:
        __str__(): Возвращает строковое представление объекта назначения.

    """
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    appointment_date = models.DateTimeField('Дата назначения')

    def __str__(self):
        """
        Возвращает строковое представление объекта назначения.

        Returns:
            str: Строковое представление объекта назначения в формате "Доктор: <имя врача>, Пациент: <имя пациента>,
                 Упражнение: <название упражнения>".
        """
        return f"Доктор: {self.doctor.name}, Пациент: {self.patient.name}, Упражнение: {self.exercise.title}"

api/views.py
import json

from django.core.exceptions import ValidationError
from django.db.models import QuerySet
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import View

from api.models import Doctor, Patient, Exercise, Appointment


def api(request):
    """
    Вью для отображения главной страницы API.

    Parameters:
        request (HttpRequest): Объект запроса от клиента.

    Returns:
        HttpResponse: HTTP-ответ с содержимым '<h1>API page</h1>', которое будет отображено на странице клиента.

    Example:
        Пример использования в URL-маршрутах:
        ```
        urlpatterns = [
            path('', views.api, name='api'),
        ]
        ```
    """
    return HttpResponse('<h1>API page</h1>')


class DoctorView(View):
    """
    Класс представления для работы с доктором.

    """

    def get(self, request, pk=None):
        """
        Обработчик GET-запроса для отображения списка докторов или деталей конкретного доктора.

        Parameters:
            request (HttpRequest): Объект запроса от клиента.
            pk (int, optional): ID доктора. Если указан, то отображаются детали конкретного доктора.

        Returns:
            HttpResponse: HTTP-ответ с отображением списка докторов или деталей конкретного доктора.

        Raises:
            Http404: Если не найден доктор с указанным ID (при запросе деталей конкретного доктора).
        """

        template = 'api/html/doctor.html'

        if pk is not None:
            doctors = get_object_or_404(Doctor, pk=pk)

            template = 'api/html/doctor_exercises.html' \
                if request.path.endswith('exercises/') \
                else template
        else:
            doctors = Doctor.objects.all()

        return render(
            request,
            template,
            context={'doctors': doctors if isinstance(doctors, QuerySet) else [doctors]}
        )

    def post(self, request, pk=None):
        """
        Обработчик POST-запроса для создания нового доктора или назначения упражнения пациенту.

        Parameters: request (HttpRequest): Объект запроса от клиента. pk (int, optional): ID доктора. Если НЕ указан,
        то создается заданный в body доктор, если УКАЗАН, то происходит назначение упражнения заданному в body пациенту.

        Returns:
            HttpResponse: JSON ответ с успешностью создания доктора или назначения лекарства.

        Raises:
            Http404: Если не найден доктор с указанным ID.
            Http400: Если неверно указаны данные в body.
        """

        if pk is not None and request.path.endswith('appoint/'):
            try:
                data = json.loads(request.body.decode('utf-8'))
                patient_id = data['patient_id']
                exercise_id = data['exercise_id']
                doctor = Doctor.objects.get(pk=pk)
                exercise = Exercise.objects.get(pk=exercise_id)
                patient = Patient.objects.get(pk=patient_id)

                if exercise.specialisations.filter(pk=doctor.speciality.pk).exists():
                    if patient in doctor.patients.all():
                        appointment_exists = Appointment.objects.filter(doctor=doctor, patient=patient,
                                                                        exercise=exercise).exists()
                        if appointment_exists:
                            return JsonResponse(
                                {
                                    'status': 'error',
                                    'message': 'Такое назначение уже существует.'
                                },
                                status=400
                            )
                        else:
                            # Создаем новую запись в таблице Appointment
                            appointment = Appointment(
                                doctor=doctor,
                                patient=patient,
                                exercise=exercise,
                                appointment_date=timezone.now()  # Используем из модуля django.utils.timezone
                            )
                            appointment.full_clean()
                            appointment.save()

                            return JsonResponse(
                                {
                                    'status': 'success',
                                    'message': 'Назначение успешно создано.'
                                }
                            )
                    else:
                        return JsonResponse(
                            {
                                'status': 'error',
                                'message': 'Данный доктор не имеет разрешения назначать упражнения данному пациенту.'
                            },
                            status=400
                        )
                else:
                    return JsonResponse(
                        {
                            'status': 'error',
                            'message': 'Данный доктор не имеет необходимой специальности для назначения этого '
                                       'упражнения.'
                        },
                        status=400
                    )
            except (ValidationError, KeyError) as e:
                return JsonResponse(
                    {
                        'status': 'error',
                        'message': str(e)
                    },
                    status=400
                )

        try:
            data = json.loads(request.body.decode('utf-8'))
            doctor = Doctor(
                name=data['name'],
                speciality_id=data['speciality']
            )

            doctor.full_clean()
            doctor.save()

            return JsonResponse(
                {
                    'status': 'success',
                    'message': 'Доктор успешно создан.'
                }
            )
        except ValidationError as e:
            return JsonResponse(
                {
                    'status': 'error',
                    'message': str(e)
                },
                status=400
            )

    def put(self, request, pk):
        """
        Обработчик PUT-запроса для обновления данных о докторе.

        Parameters:
            request (HttpRequest): Объект запроса от клиента.
            pk (int): ID доктора, которого нужно обновить.

        Returns:
            JsonResponse: JSON-ответ с информацией об успешном обновлении или ошибке.

        Raises:
            Http404: Если не найден доктор с указанным ID.
        """

        try:
            data = json.loads(request.body.decode('utf-8'))
            doctor = get_object_or_404(Doctor, pk=pk)
            doctor.name = data['name']
            doctor.speciality_id = data['speciality']

            doctor.full_clean()
            doctor.save()

            return JsonResponse(
                {
                    'status': 'success',
                    'message': 'Доктор успешно обновлен.'
                }
            )
        except ValidationError as e:
            return JsonResponse(
                {
                    'status': 'error',
                    'message': str(e)
                },
                status=400
            )

    def patch(self, request, pk):
        """
        Обработчик PATCH-запроса для частичного обновления данных о докторе.

        Parameters:
            request (HttpRequest): Объект запроса от клиента.
            pk (int): ID доктора, которого нужно обновить.

        Returns:
            JsonResponse: JSON-ответ с информацией об успешном обновлении или ошибке.

        Raises:
            Http404: Если не найден доктор с указанным ID.

        """

        try:
            data = json.loads(request.body.decode('utf-8'))
            doctor = get_object_or_404(Doctor, pk=pk)
            if 'name' in data:
                doctor.name = data['name']
            if 'speciality' in data:
                doctor.speciality_id = data['speciality']

            doctor.full_clean()
            doctor.save()

            return JsonResponse(
                {
                    'status': 'success',
                    'message': 'Доктор успешно обновлен.'
                }
            )
        except ValidationError as e:
            return JsonResponse(
                {
                    'status': 'error',
                    'message': str(e)
                },
                status=400
            )

    def delete(self, request, pk):
        """
        Обработчик DELETE-запроса для удаления доктора.

        Parameters:
            request (HttpRequest): Объект запроса от клиента.
            pk (int): ID доктора, которого нужно удалить.

        Returns:
            JsonResponse: JSON-ответ с информацией об успешном удалении.

        Raises:
            Http404: Если не найден доктор с указанным ID.

        """

        doctor = get_object_or_404(Doctor, pk=pk)
        doctor.delete()

        return JsonResponse(
            {
                'status': 'success',
                'message': 'Доктор успешно удален.'
            }
        )


class PatientView(View):
    """
    Класс представления для работы с пациентом.

    """

    def get(self, request, pk=None):
        """
        Обработчик GET-запроса для получения информации о пациентах.

        Parameters:
            request (HttpRequest): Объект запроса от клиента.
            pk (int, optional): ID пациента, если указан - возвращает информацию о конкретном пациенте.
                                        Если None - возвращает информацию обо всех пациентах.

        Returns:
            HttpResponse: Ответ с отображением информации о пациентах.

        Raises:
            Http404: Если не найден пациент с указанным ID.

        """

api/templates/api/html/base.html
{% load static %}
{% load compile_static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>API</title>

    <link rel="stylesheet" href="{% static "styles/reset.less"|compile %}"/>
    <link rel="stylesheet" href="{% static "styles/base.less"|compile %}"/>
</head>
<body>

<main class="main">
    {% block main %} {% endblock %}
</main>

</body>
</html>

api/templates/api/html/doctor.html
{% extends 'api/html/base.html' %}

{% load static %}
{% load compile_static %}

{% block main %}

    <table>
        <h1>Doctors Information</h1>
        <tr>
            <th>Name</th>
            <th>Speciality</th>
            <th>Patients</th>
        </tr>
        {% for doctor in doctors %}
            <tr>
                <td>{{ doctor.name }}</td>
                <td>{{ doctor.speciality }}</td>
                <td>
                    {% for patient in doctor.patients.all %}
                        {{ patient.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

api/templates/api/html/doctor_exercises.html
{% extends 'api/html/base.html' %}
{% load static %}
{% load compile_static %}

{% block main %}
    {% for doctor in doctors %}
        <h1>Врач: {{ doctor.name }}</h1>
        <h2>Упражнения, которые данный врач назначил</h2>
        <table>
            <tr>
                <th>Пациент</th>
                <th>Упражнение</th>
                <th>Описание</th>
                <th>Частота</th>
            </tr>
            {% for appointment in doctor.appointment_set.all %}
                <tr>
                    <td>{{ appointment.patient.name }}</td>
                    <td>{{ appointment.exercise.title }}</td>
                    <td>{{ appointment.exercise.description }}</td>
                    <td>{{ appointment.exercise.get_frequency_display }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}
{% endblock %}

api/templates/api/html/exercise.html
{% extends 'api/html/base.html' %}

{% block main %}

    <h1>Exercises Information</h1>
    <table>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Frequency</th>
            <th>Specializations</th>
        </tr>
        {% for exercise in exercises %}
            <tr>
                <td>{{ exercise.title }}</td>
                <td>{{ exercise.description }}</td>
                <td>{{ exercise.get_frequency_display }}</td>
                <td>
                    {% for speciality in exercise.specialisations.all %}
                        {{ speciality.title }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

api/templates/api/html/patient.html
{% extends 'api/html/base.html' %}

{% block main %}

    <h1>Patients Information</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Assigned Doctors</th>
        </tr>
        {% for patient in patients %}
            <tr>
                <td>{{ patient.name }}</td>
                <td>
                    {% for doctor in patient.doctor_set.all %}
                        {{ doctor.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

api/templates/api/html/patient_exercises.html
{% extends 'api/html/base.html' %}
{% load static %}
{% load compile_static %}

{% block main %}
    {% for patient in patients %}
        <h1>Пациент: {{ patient.name }}</h1>
        <h2>Назначенные пациенту упражнения</h2>
        <table>
            <tr>
                <th>Врач</th>
                <th>Упражнение</th>
                <th>Описание</th>
                <th>Частота</th>
            </tr>
            {% for appointment in patient.appointment_set.all %}
                <tr>
                    <td>{{ appointment.doctor.name }}</td>
                    <td>{{ appointment.exercise.title }}</td>
                    <td>{{ appointment.exercise.description }}</td>
                    <td>{{ appointment.exercise.get_frequency_display }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}
{% endblock %}